### ISSUE TITLE
A little update

### ISSUE THREAD

**Issue by aldostools** [NzV/MAMBA_PRX_Loader#2]
- Added the payloads for 4.60 DEX, 4.75 DEX, 4.76 CEX/DEX. 
- Fixed minor bug: 4.66 CEX was detected as 4.65 CEX 
http://aldostools.org/temp/test/MAMBA_PRX_Loader-master_2.1.4_(mod_by_aldo).rar

PS. I haven't tested them, but IMO the offsets are ok. No need to mention me in the credits.

**Comment by NzV** [comment]
Thx, i have updated the github repo.

**Comment by aldostools** [comment]
:+1:
